pluginManagement {
    plugins {
        kotlin("jvm") version "1.9.22"
    }
}
/*
 * This file was generated by the Gradle 'init' task.
 */

rootProject.name = "java-testing-learning"
include("cucumber")
include("mock-server")
include("wiremock")
